services:
  - type: web
    name: fastapi-video-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn kunj:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
